flowchart TD

A[Fiscal Document]

A --> B[Issuer]

B --> C[Establishment]

C --> D[Point Of Issue]

D --> E[Sequence]

E --> F[CDC]

F --> G[Payload JSON]

G --> H[Schema-Oriented Unsigned XML]

H --> I[Accepted]
