[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$ROj9vzcGoNSak7LWWguhlA$fz/9hl8PtDik3no4e3ywGsDlbRX79f0aI8lxtKh6mbCNPL3lpE0cAZVxqINhtMabgi5gTcZx.kuKF93kQGpKOA
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
xmlrpc_port = 8069
log_level = info

