{
    "name": "Electronic Invoicing Paraguay",
    "summary": "Paraguay fiscal configuration for the e-Invoice core",
    "version": "17.0.1.0.0",
    "category": "Accounting/Accounting",
    "depends": ["einvoice_module"],
    "external_dependencies": {
        "python": ["reportlab"],
    },
    "data": [
        "security/ir.model.access.csv",
        "security/fiscal_py_security_rules.xml",
        "data/py_sifen_retry_cron.xml",
        "views/fiscal_py_issuer_views.xml",
        "views/fiscal_py_economic_activity_views.xml",
        "views/fiscal_py_establishment_views.xml",
        "views/fiscal_py_point_of_issue_views.xml",
        "views/fiscal_py_timbrado_views.xml",
        "views/fiscal_py_csc_views.xml",
        "views/fiscal_py_sequence_views.xml",
        "views/fiscal_document_views.xml",
        "views/einvoice_py_menus.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
